name: CI

on: [push]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew --stacktrace :backend:clean
      - run: ./gradlew --stacktrace :backend:test
      - run: ./gradlew --stacktrace :backend:lint

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: "14.x"
      - run: ./gradlew --stacktrace :frontend:test
      - run: ./gradlew --stacktrace :frontend:lint

  end-to-end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: cypress-io/github-action@v2
        with:
          working-directory: cypress
          start: npm run application:start
          wait-on: "http://localhost:8080"
          wait-on-timeout: 500
